name: Deploy to Vercel

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Nuxt
        run: pnpm build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Debug tokens
        run: |
          echo "APP length: ${#APP_URL}"
          echo "URL length: ${#SUPABASE_URL}"
          echo "ANON_KEY length: ${#SUPABASE_ANON_KEY}"
          echo "TOKEN length: ${#VERCEL_TOKEN}"
          echo "ORG_ID length: ${#VERCEL_ORG_ID}"
          echo "PROJECT_ID length: ${#VERCEL_PROJECT_ID}"
        env:
          APP_URL: ${{ secrets.APP_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        run: |
          npm i -g vercel

          vercel pull --yes --environment=production \
            --token=$VERCEL_TOKEN \
            --org=$VERCEL_ORG_ID \
            --project=$VERCEL_PROJECT_ID

          vercel build --prod \
            --token=$VERCEL_TOKEN \
            --org=$VERCEL_ORG_ID \
            --project=$VERCEL_PROJECT_ID

          vercel deploy --prebuilt --prod \
            --token=$VERCEL_TOKEN \
            --org=$VERCEL_ORG_ID \
            --project=$VERCEL_PROJECT_ID
        env:
          APP_URL: ${{ secrets.APP_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
